const state={user:JSON.parse(localStorage.getItem("rr_user")||"null"),orders:JSON.parse(localStorage.getItem("rr_orders")||"[]"),notifications:JSON.parse(localStorage.getItem("rr_notifications")||"[]")};
function save(){localStorage.setItem("rr_user",JSON.stringify(state.user));localStorage.setItem("rr_orders",JSON.stringify(state.orders));localStorage.setItem("rr_notifications",JSON.stringify(state.notifications))}
function toast(msg){const t=document.getElementById("toast");t.textContent=msg;t.style.display="block";setTimeout(()=>t.style.display="none",2600)}
function enterSite(){document.getElementById("ageGate").style.display="none";localStorage.setItem("rr_age_ok","1")}
if(localStorage.getItem("rr_age_ok")==="1")document.getElementById("ageGate").style.display="none";
function toggleMenu(){document.getElementById("nav").classList.toggle("show")}function closeMenu(){document.getElementById("nav").classList.remove("show")}
function openModal(id){document.getElementById(id).classList.add("open")}function closeModal(id){document.getElementById(id).classList.remove("open")}
function requireLogin(next){if(state.user)return true;localStorage.setItem("rr_after_login",next);openModal("loginModal");return false}
function sendOtp(){const p=document.getElementById("phone").value.trim();if(!/^\d{10}$/.test(p)){toast("Enter a valid 10-digit mobile number");return}document.getElementById("otpArea").hidden=false;toast("Demo OTP sent. Use 123456.")} 
function verifyOtp(){if(document.getElementById("otp").value!=="123456"){toast("Invalid OTP");return}state.user={phone:document.getElementById("phone").value.trim(),name:"RIYA ROY User",joined:new Date().toISOString()};state.notifications.unshift({text:"Welcome to RIYA ROY Creation",date:new Date().toLocaleString()});save();closeModal("loginModal");toast("Login successful");const n=localStorage.getItem("rr_after_login");localStorage.removeItem("rr_after_login");if(n==="account")openAccount();else if(n)window[n]&&window[n]()}
function openAccount(){if(!requireLogin("account"))return;const u=state.user;const active=state.orders.find(o=>o.type==="membership"&&o.status==="Success"&&new Date(o.expiry)>new Date());document.getElementById("accountBody").innerHTML=`<div class="stat"><strong>${u.name}</strong><small>${u.phone}</small></div><div class="admin-grid" style="margin-top:14px"><div class="stat"><strong>${active?"Active":"Inactive"}</strong><small>Membership Status</small></div><div class="stat"><strong>${active?new Date(active.expiry).toLocaleDateString():"—"}</strong><small>Membership Expiry</small></div><div class="stat"><strong>${state.orders.filter(o=>o.type!=="membership").length}</strong><small>Purchases / Orders</small></div></div><h3>My Purchases</h3>${state.orders.length?state.orders.map(o=>`<div class="order"><strong>${o.title}</strong><br><small>${o.status} • ₹${o.amount||0} • ${o.id}</small></div>`).join(""):"<p>No purchases yet.</p>"}<h3>Notifications</h3>${state.notifications.length?state.notifications.slice(0,10).map(n=>`<div class="order">${n.text}<br><small>${n.date}</small></div>`).join(""):"<p>No notifications.</p>"}`;openModal("accountModal")}
let pendingPay=null;
function openPayment(title,amount,type,meta={}){pendingPay={title,amount,type,meta};document.getElementById("payTitle").textContent=title;document.getElementById("payAmount").textContent="₹"+amount;document.getElementById("upiLink").href=`upi://pay?pa=917679669353@upi&pn=RIYA%20ROY%20Creation&am=${amount}&cu=INR`;openModal("paymentModal")}
function buyContent(title,category,amount){if(!requireLogin(()=>buyContent(title,category,amount)))return;openPayment(title,amount,"content",{category})}
function buyMembership(plan,amount){if(!requireLogin(()=>buyMembership(plan,amount)))return;openPayment(`${plan} Membership`,amount,"membership",{plan})}
function submitPromotion(e){e.preventDefault();if(!requireLogin(()=>submitPromotion(e)))return;const service=document.getElementById("promoService").value;const date=document.getElementById("promoDate").value;const link=document.getElementById("promoLink").value;const amount=service.includes("₹15")?15:service.includes("₹30")?30:0;if(amount===0){toast("Custom Promotion: contact for price");return}openPayment("Promotion — "+service,amount,"promotion",{service,date,link})}
function submitCollab(e){e.preventDefault();if(!requireLogin(()=>submitCollab(e)))return;const order={id:"COL-"+Date.now(),type:"collaboration",title:document.getElementById("productName").value,amount:0,status:"New",date:new Date().toISOString(),meta:{brand:document.getElementById("brandName").value,contact:document.getElementById("contactPerson").value,mobile:document.getElementById("brandMobile").value,email:document.getElementById("brandEmail").value,type:document.getElementById("collabType").value,budget:document.getElementById("budget").value,message:document.getElementById("collabMessage").value,date:document.getElementById("preferredDate").value}};state.orders.unshift(order);state.notifications.unshift({text:"Brand collaboration request submitted",date:new Date().toLocaleString()});save();toast("Collaboration request submitted");e.target.reset()}
function markPaymentPending(){if(!pendingPay)return;const id="RR-"+Date.now();const o={id,type:pendingPay.type,title:pendingPay.title,amount:pendingPay.amount,status:"Pending",date:new Date().toISOString(),meta:pendingPay.meta};if(pendingPay.type==="membership"){const days=pendingPay.meta.plan==="Monthly"?30:pendingPay.meta.plan==="3 Months"?90:365;o.expiry=new Date(Date.now()+days*86400000).toISOString()}state.orders.unshift(o);state.notifications.unshift({text:"Payment Pending — verification required",date:new Date().toLocaleString()});save();closeModal("paymentModal");toast("Payment marked Pending. Gateway verification is required for automatic unlock.");}
function legal(title){event.preventDefault();alert(title+"\n\nRIYA ROY Creation\nNo Refund Policy\nPrivacy and Terms page content should be finalized before production deployment.")}
function showAdmin(){openModal("adminModal");const payments=state.orders.filter(o=>["membership","content","promotion"].includes(o.type));document.getElementById("adminStats").innerHTML=`<div class="stat"><strong>₹${payments.filter(o=>o.status==="Success").reduce((a,o)=>a+o.amount,0)}</strong><small>Total Successful Earnings</small></div><div class="stat"><strong>${state.orders.filter(o=>o.type==="membership"&&o.status==="Success").length}</strong><small>Active/Successful Members</small></div><div class="stat"><strong>${state.orders.filter(o=>o.type==="content"&&o.status==="Success").length}</strong><small>Single Content Sales</small></div><div class="stat"><strong>${state.orders.filter(o=>o.type==="promotion").length}</strong><small>Promotion Orders</small></div><div class="stat"><strong>${state.orders.filter(o=>o.type==="collaboration").length}</strong><small>Brand Collaborations</small></div><div class="stat"><strong>${state.orders.filter(o=>o.status==="Pending").length}</strong><small>Pending Payments</small></div>`;document.getElementById("adminOrders").innerHTML="<h3>Recent Orders</h3>"+(state.orders.length?state.orders.slice(0,20).map(o=>`<div class="order"><strong>${o.title}</strong> — ₹${o.amount||0}<br><small>${o.id} • ${o.status} • ${new Date(o.date).toLocaleString()}</small>${o.status==="Pending"?`<br><button class="btn small primary" onclick="adminSuccess('${o.id}')">Mark Success</button>`:""}</div>`).join(""):"<p>No orders yet.</p>")}
function adminSuccess(id){const o=state.orders.find(x=>x.id===id);if(!o)return;o.status="Success";state.notifications.unshift({text:`Payment Successful — ${o.title}`,date:new Date().toLocaleString()});save();toast("Payment marked Success");showAdmin()}
window.addEventListener("keydown",e=>{if(e.key==="Escape")document.querySelectorAll(".modal.open").forEach(m=>m.classList.remove("open"))});
window.openAdmin=showAdmin;
